### PR TITLE
specify the languages to display

### PR DESCRIPTION
**Pull request by ahmedash95**
some improvements as mentioned in #19  . i made some additional on langman:show command , this PR will allow users to specify the languages that they want to display like

```
php artisan langman:show auth --lang=en
```

for multiple specifications

```
php artisan langman:show auth --lang=en,ar
```

### CODE REVIEW

**Comment by themsaid** [comment]
@ahmedash95 how about 

`php artisan langman:show auth->en`

`php artisan langman:show auth->en,ar`

`php artisan langman:show auth.username->en`

To match the syntax of the other commands?

**Comment by ahmedash95** [comment]
@themsaid then i think we will move the specification from the ShowCommand to Manager ?

**Comment by ahmedash95** [comment]
@themsaid i don't now why this chaining confusing me , why don't we just use option lang in any command ?

**Comment by rsdev000** [comment]
+1 for ```php artisan langman:show auth --lang=en,ar``` 

In my opinion this syntax is more suitable for a command.

**Pull request merged**
