### PR TITLE
Sync views with app files

### PR DESCRIPTION
**Pull request by ahmedash95**
as mentioned in #21  , sync just working with views paths , in this PR the sync working with all views and app subdirectories , i don't know if the global app_path is fine or i have to specify some directories only but i think we need any lang method used in app or view path

### CODE REVIEW

**Comment by themsaid** [comment]
Here's why StyleCI failed: https://styleci.io/analyses/XNAvjy

For the test cases failure, it's because you updated the code without updating the tests.

**Comment by ahmedash95** [comment]
@themsaid the wired thing is that if i create a fresh installation of laravel then required langman package and run tests it fails !! . 

i will fix all failed checks

**Comment by ahmedash95** [comment]
@themsaid i think you missed out the asserting of keys that collected from app path in the modification after merge me  PR . or you purposed it ? 

https://github.com/themsaid/laravel-langman/blob/master/tests/SyncCommandTest.php

**Comment by ahmedash95** [comment]
oh sorry i see that you revert sync command test in commits .. but may i ask why you removed it .. or it doesn't matter to test

**Comment by themsaid** [comment]
The script will look into all directories provided in the third argument of `Manager`, that said it doesn't matter what directories we add. So the functionality will work on views directory as well as app directory.

**Comment by ahmedash95** [comment]
thanks for replay .. i got it now :)

**Pull request merged**
