### PR TITLE
specify the languages to display

### PR DESCRIPTION
**Pull request by ahmedash95**
some improvements as mentioned in #19 . i made some additional on langman:show command , this PR will allow users to specify the languages that they want to display like 

```
php artisan langman:show auth --lang=en
``` 

for multiple specifications 

```
php artisan langman:show auth --lang=en,ar
```

### CODE REVIEW

**Comment by themsaid** [comment]
Don't mind StyleCI, it'll automatically fix the style once merged 👍

**Comment by ahmedash95** [comment]
@themsaid  i think i miss some validations on option --lang, let me fix it

**Comment by themsaid** [comment]
@ahmedash95 how about 

`php artisan langman:show auth->en`

`php artisan langman:show auth->en,ar`

`php artisan langman:show auth.username->en`

To match the syntax of the other commands.

**Comment by ahmedash95** [comment]
@themsaid then i think we will move the specification from the ShowCommand to Manager ?

**Pull request closed without merging**
